all:
	@echo "Compiling module objects..."
	$(MAKE) -C objects
	@echo "Compiling module types..."
	$(MAKE) -C types

clean:
	@echo "Clean module objects..."
	$(MAKE) -C objects clean
	@echo "Clean module types..."
	$(MAKE) -C types clean